import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";

import type { ApiError } from "../api/client";
import {
  generateJd,
  getJdVersions,
  saveJd,
  type JdVersion,
} from "../api/endpoints/rrfs";
import { useAuth } from "../auth/AuthContext";
import { AgentResultCard } from "./AgentResultCard";

const WRITE_ROLES = ["ADMIN", "HR", "HIRING_MANAGER"];

/**
 * JD versions panel for the RRF detail page (T-203). Generates a JD via the jd_creation agent,
 * shows version history (agent vs. manual), and lets HM/HR hand-edit and save a new version
 * before submission. Read-only for roles outside WRITE_ROLES (e.g. BU_HEAD).
 */
export function JdPanel({ rrfId }: { rrfId: string }) {
  const { user } = useAuth();
  const canWrite = user ? WRITE_ROLES.includes(user.role) : false;
  const qc = useQueryClient();

  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState("");
  const [error, setError] = useState<string | null>(null);

  const versionsQ = useQuery({
    queryKey: ["jd", rrfId],
    queryFn: () => getJdVersions(rrfId),
  });
  const versions = useMemo<JdVersion[]>(() => versionsQ.data ?? [], [versionsQ.data]);
  const selected =
    versions.find((v) => v.jd_id === selectedId) ?? versions[0] ?? null;

  function afterWrite(v: JdVersion) {
    setError(null);
    setSelectedId(v.jd_id);
    setEditing(false);
    qc.invalidateQueries({ queryKey: ["jd", rrfId] });
  }

  const genM = useMutation({
    mutationFn: () => generateJd(rrfId),
    onSuccess: (res) => afterWrite(res.version),
    onError: (e) => setError((e as unknown as ApiError).message ?? "JD generation failed"),
  });

  const saveM = useMutation({
    mutationFn: () => saveJd(rrfId, draft),
    onSuccess: afterWrite,
    onError: (e) => setError((e as unknown as ApiError).message ?? "Save failed"),
  });

  return (
    <AgentResultCard
      title="Job Description"
      subtitle="Generated by the jd_creation agent from the requisition; editable before submit."
      actionLabel={canWrite ? (versions.length ? "Re-generate" : "Generate JD") : undefined}
      onAction={canWrite ? () => genM.mutate() : undefined}
      busy={genM.isPending}
    >
      {error && (
        <p className="error-text" style={{ marginTop: 0 }}>
          {error}
        </p>
      )}

      {versionsQ.isLoading ? (
        <p style={{ color: "var(--muted)" }}>Loading versions…</p>
      ) : versions.length === 0 ? (
        <p style={{ color: "var(--muted)" }}>
          No JD yet. {canWrite ? "Generate one with the button above." : ""}
        </p>
      ) : (
        <>
          {/* version history selector */}
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginBottom: 14 }}>
            {versions.map((v) => {
              const active = selected?.jd_id === v.jd_id;
              return (
                <button
                  key={v.jd_id}
                  onClick={() => {
                    setSelectedId(v.jd_id);
                    setEditing(false);
                  }}
                  style={{
                    background: active ? "var(--brand)" : "#eef2fb",
                    color: active ? "var(--brand-ink)" : "var(--brand)",
                    padding: "6px 12px",
                    fontSize: "0.82rem",
                  }}
                  title={new Date(v.created_at).toLocaleString()}
                >
                  v{v.version_no} · {v.generated_by_agent ? "AI" : "manual"}
                </button>
              );
            })}
          </div>

          {editing ? (
            <>
              <textarea
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                rows={18}
                style={{
                  width: "100%",
                  fontFamily: "monospace",
                  fontSize: "0.85rem",
                  padding: 12,
                  border: "1px solid var(--border)",
                  borderRadius: 8,
                  resize: "vertical",
                }}
              />
              <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
                <button onClick={() => saveM.mutate()} disabled={saveM.isPending || !draft.trim()}>
                  {saveM.isPending ? "Saving…" : "Save as new version"}
                </button>
                <button
                  onClick={() => setEditing(false)}
                  style={{ background: "#eef2fb", color: "var(--brand)" }}
                >
                  Cancel
                </button>
              </div>
            </>
          ) : (
            <>
              <pre
                style={{
                  whiteSpace: "pre-wrap",
                  wordBreak: "break-word",
                  background: "var(--bg)",
                  border: "1px solid var(--border)",
                  borderRadius: 8,
                  padding: 16,
                  margin: 0,
                  fontFamily: "inherit",
                  fontSize: "0.9rem",
                  lineHeight: 1.5,
                  maxHeight: 420,
                  overflow: "auto",
                }}
              >
                {selected?.jd_markdown}
              </pre>
              {canWrite && selected && (
                <button
                  onClick={() => {
                    setDraft(selected.jd_markdown);
                    setEditing(true);
                    setError(null);
                  }}
                  style={{ marginTop: 12, background: "#eef2fb", color: "var(--brand)" }}
                >
                  Edit
                </button>
              )}
            </>
          )}
        </>
      )}
    </AgentResultCard>
  );
}
